name: "ci labels"

on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Script
        uses: actions/github-script@v6.4.0
        with:
          script: |
            github.rest.issue.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["enhancement"]
            })
