name: Label PR
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: netlify/pr-labeler-action@v1.0.0
        if: contains(github.event.pull_request.title, 'feat')
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          label: "Feature"

      - uses: netlify/pr-labeler-action@v1.0.0
        if: contains('['refactor' , '리팩토링']' ,github.event.pull_request.title)
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          label: "refactor"
